// dotnet/_.cs
// Global Usings
global using System;
global using System.Buffers;
global using System.Buffers.Binary;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Drawing;
global using System.Drawing.Drawing2D;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Net.NetworkInformation;
global using System.Net.Sockets;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows.Forms;
global using Microsoft.Win32;
